### ISSUE TITLE
GitHub Actions workflow for docker job

### ISSUE THREAD

**Issue by mjbear** [hellt/markdown-footnote-sorter#11]
Hello @hellt,

Thank you for the second set of eyes on PRs and responding to issues (such as this one).

When anyone other than yourself puts in a PR, it's possible to avoid that failed Actions run. My thought is we skip the docker job unless a certain circumstance is met.

I've been kicking the tires on GH Actions so I'll have something handy as a PR once I know which direction we want to go.

So my question here is what workflow are you thinking?
1. Do you build a new Docker image on each PR merge?
    * (doesn't seem that we'd want it this way)
1. Do you _only_ build a Docker image upon a Release being cut?
    * (seems the most logical to me)

:grinning: Thank you! :grinning:

**Comment by hellt** [comment]
Hi
yes, it was intentional to build an image on each commit basically, even on PRs, so that it would be possible to send someone a sha:x tagged image for testing.

But this obv doesn't work when a non repo owner triggers the workflow, hence it is failing when you do the push action.

I am fine with removing this step and only do the image build on release and pushes to main. I can do the draft releases if I need to create an image from the non-merged PR

**Comment by mjbear** [comment]
> Hi yes, it was intentional to build an image on each commit basically, even on PRs, so that it would be possible to send someone a sha:x tagged image for testing.

Gotcha. Makes sense - thank you for explaining!

> 
> But this obv doesn't work when a non repo owner triggers the workflow, hence it is failing when you do the push action.
> 
> I am fine with removing this step and only do the image build on release and pushes to main. I can do the draft releases if I need to create an image from the non-merged PR

It could be set on PR merge (closed) instead -- does that sound like a reasonable configuration?
That would be a middle ground (granted it isn't the sha:x tag).

**Comment by mjbear** [comment]
PR #12 is ready for review :tada:
